#登陆相关配置
login:
  #开放的模拟登陆api服务器地址 
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"

#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    - default:
        #表单项标题
        title: 当前您的所在地是？
        #表单项类型，对应今日校园接口返回的fieldType字段，1代表文本，2代表单选，3代表多选，4代表图片
        type: 1
        #表单项默认值, 三级选项选择用 '/' 分隔
        value: 安徽省/阜阳市/阜南县
    - default:
        title: 今天您的体温是多少？
        type: 2
        value: 小于37.3℃   
    - default:
        title: 今天您的身体状况是？
        type: 2
        value: 体温等一切正常
    - default:
        title: 今天您的苏康码颜色是？
        type: 2
        value: 绿码
    - default:
        title: 今天您的行程卡颜色是？
        type: 2
        value: 绿码
    - default:
        title: 近28天内，您或您的共同生活人员是否有境外旅居史？
        type: 2
        value: 否
    - default:
        title: 近21天内，您或您的共同生活人员是否有国内中高风险地区及所在县（市、区、旗）旅居史？
        type: 2
        value: 否
    - default:
        title: 近21天内，您或您的共同生活人员是否与确诊病例（含无症状感染者）有轨迹交叉？ 
        type: 2
        value: 否
    - default:
        title: 近14天内，您或您的共同生活人员是否是确诊或疑似病例？
        type: 2
        value: 否
    - default:
        title: 预计您新学期返校日期是？
        type: 1
        value: 2022-08-28
    - default:
        title: 本人是否承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处？    
        type: 2
        value: 是
